version: '3'
services:
  db:
    image: mariadb:10.2
    container_name: db
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql
volumes:
  mariadbdata:a